### PR TITLE
Include format_bytes filter to print human readable file-size values

### PR DESCRIPTION
**Pull request by thePanz**
This is a first implementation, I think that some "love" would be required for a feature-complete filter

### CODE REVIEW

**Comment by thePanz** [comment]
Dear All, seems that no-one is interested in this patch and I have created a new extension (that includes these patches) here: https://github.com/thePanz/Twig-Extension-Number

Seems that the Twig-Extensions needs some love :)

**Comment by hason** [comment]
:+1:

@thePanz I like your extension. Thanks!

**Comment by Trainmaster** [comment]
Any update on this? And what about naming this extension `unit` so we are able to add further unit formatting/conversion later on?

**Comment by SpacePossum** [comment]
I've made one for SI;
https://github.com/GeckoPackages/GeckoTwig#sifilter
and bits vs. bytes;
https://github.com/GeckoPackages/GeckoTwig#bytesfilter

would be nice to see more filters here or have a doc. with a list of 3rd party filters  ^-^

**Comment by fabpot** [comment]
Closing as there are extensions (mentioned here) that implemented that.

**Pull request closed without merging**
