### PR TITLE
Allow Twig 3

### PR DESCRIPTION
**Pull request by garak**
This should fix issue #257

### CODE REVIEW

**Comment by stof** [comment]
@fabpot does this make sense, given that the goal is to deprecate this repo ?

**Comment by garak** [comment]
Ah, I didn't know about possible deprecations.
Tried to find some infos about that, but couldn't find anything.
Even [docs for Twig 3](https://twig.symfony.com/doc/3.x/advanced.html#creating-an-extension) still mention this repo

**Comment by stof** [comment]
Well, several of the extensions in this repo have been replaced by the new `twig/*-extra` packages (not a drop-in replacement, as exposed filters and functions are not exactly the same).

Putting all extensions in the same composer package has many drawbacks:

- cannot manage dependencies properly (all deps other than twig itself have to be optional as only one of the extensions will need them and it might not be the one you use)
- cannot auto-register extensions in Symfony Flex (as we don't know which one you want to use)
- it pushes everyone to submit their own extensions to be managed by Fabien instead of maintaining them on their own, which does not create an healthy ecosystem (most of the extensions in Twig-extensions are badly maintained because Fabien does not use them and original contributors don't help maintain them)

**Comment by garak** [comment]
I got the picture, except for the role of twig-extra-bundle, that's putting everything together again.

**Comment by stof** [comment]
twig-extra-bundle is responsible for registering the extensions from the `twig/*-extra` packages when the package is installed (and also registers a callback to suggest installing the appropriate `twig/*-extra` package when trying to use a filter or function provided by one of them and it does not exist)

**Comment by garak** [comment]
So I guess that this PR and related issue can be closed without merge, but I also guess that such deprecation should be highlighted somewhere (in README of this repo for sure, probably also in Twig docs).
Let's see what Fabien thinks about it

**Comment by stof** [comment]
Well, my comment is based on the fact that most existing PRs and issues have been closed recently with a comment like that: https://github.com/twigphp/Twig-extensions/pull/254#issuecomment-543016705

**Comment by fabpot** [comment]
This repository is indeed obsolete now.
I've removed the mentions in the official docs here: https://github.com/twigphp/Twig/pull/3200
See #259 for the update on the README file.

**Comment by kylekatarnls** [comment]
Hi @fabpot you should also remove it from there:
https://symfony.com/doc/current/templating/twig_extension.html

Symfony 5 documentation suggests to:
`composer require twig/extensions`

I'm trying to make my twig extension compatible with Symfony 5 and Twig 3 and I must admit despite I use Symfony a lot, I'm pretty lost.

**Pull request closed without merging**
