### PR TITLE
Fixed TZ issue when the format is the abbrev

### PR DESCRIPTION
**Pull request by lyrixx**
Related to #218

### CODE REVIEW

**Comment by lyrixx** [comment]
Oh, master is broken. And this project supports very old PHP version.

@nicolas-grekas could you cleaned this projet ? :D

**Comment by patrick-99** [comment]
I fixed travis.yml but my pull request is not taken yet.

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Comment by stof** [comment]
there is a drawback with this logic: it makes the extension incompatible with the Symfony Intl polyfill: https://github.com/symfony/demo/issues/894

Should we keep running the old logic when IntlTimeZone does not exist (as we do for older PHP versions) ? Or can we polyfill that class too ?

**Comment by lyrixx** [comment]
Could we use class_exist on `IntlTimeZone` instead ?

**Comment by stof** [comment]
well, my first solution (running the old logic when it does not exist) would be implemented using `class_exists` indeed :smile:

**Pull request merged**
