### PR TITLE
Improve truncate filter to obey limit

### PR DESCRIPTION
**Pull request by dritter**
By this pull request truncate:
- obeys stricly the limit
- cuts off the last word correctly

So, if your input is `Tests are uberawesomesuper!` and you truncate at the 12th character, you'll get `Tests are...`.

This solves #129

### CODE REVIEW

**Comment by dritter** [comment]
Omg. Just saw pull request #122. I am blind.. :(

**Comment by ureimers** [comment]
Even tough, https://github.com/twigphp/Twig-extensions/pull/122 exists, I think your tests make it much clearer what both of you are trying to achieve.

I still have the feeling that it can be accomplished in much less code and there are still some edge cases that we need to agree on, e.g.:
- What if the separator is longer then the limit: `truncate('Bigword', 2, false, '...') -> '..'` ?
- What if preserving is enabled but there's only one word which is longer then the given limit: `truncate('Bigword', 6, true, '...') -> 'Bigw...' ?

But still, even though `truncate` may have been designed with HTML pages in mind, where some characters more or less won't hurt a layout, I agree with @dritter that it would be better if it was strictly obeying the limit.

**Comment by gnugat** [comment]
I'd rather let this PR fix this issue :) . I'll close mine.

**Comment by ureimers** [comment]
My current local implementation supports the following test cases:

```php
// $limit is smaller then the separator.
test('Thís is a very long sentence.', 2, false, '...', '..');
// Same behavior when preserving words.
test('Thís is a very long sentence.', 2, true, '...', '..');
// Same behavior when separator is using Unicode.
test('Thís is a very long sentence.', 1, false, '…', '…');
// Same behavior when preserving words.
test('Thís is a very long sentence.', 1, true, '…', '…');
// $limit is exactly as long as the separator.
test('Thís is a very long sentence.', 3, false, '...', '...');
// Same behavior when preserving words.
test('Thís is a very long sentence.', 3, true, '...', '...');
// Try to show as much as possible when preserving words.
test('Thís is a very long sentence.', 4, true, '...', 'T...');
// Same behavior when separator is using Unicode.
test('Thís is a very long sentence.', 4, true, '…', 'Thí…');
// Truncate unicode correctly.
test('Thís is a very long sentence.', 6, false, '...', 'Thí...');
// Whitespace is trimmed after unicode.
test('Thís is a very long sentence.', 6, false, '…', 'Thís…');
// Character after $limit is a whitespace.
test('Thís is a very long sentence.', 7, true, '...', 'Thís...');
// Separator is the same length as $limit and spans multiple words.
test('Thís is a very long sentence.', 7, true, '[..é..]', '[..é..]');
// Whitespace is trimmed before separator is added.
test('Thís is a very long sentence.', 23, false, '...', 'Thís is a very long...');
 // Making the above test more apparent.
test('Thís is a very long sentence.', 24, false, '...', 'Thís is a very long s...');
// $limit is right on the last word.
test('Thís is a very long sentence.', 23, true, '...', 'Thís is a very long...');
// $limit is right before the last character, but last char is not a whitespace.
test('Thís is a very long sentence.', 28, true, '...', 'Thís is a very long...');
// $limit is as long as the string.
test('Thís is a very long sentence.', 29, true, '...', 'Thís is a very long sentence.');
// $limit is longer than the string.
test('Thís is a very long sentence.', 30, true, '...', 'Thís is a very long sentence.');
// Separator covers multiple words.
test('Thís is a very long sentence.', 15, true, '[séparator]', 'Thís[séparator]');
// Separator is as long as the whole string.
test('Shórt one.', 30, true, '[..xXXx..]', 'Shórt one.');
```

It only changes 4 lines of code and adds one, but I don't think that I can add a PR to your PR so if we agree on these test cases than I'd create a PR on my own, referencing this.

**Comment by dritter** [comment]
@ureimers thanks for your feedback!

Regarding the edgecases:

- If the separator is longer than the limit, an exception is thrown currently. IMHO, this is the only correct thing to do, because we cannot assume what the user expects. Well this might be just an formatting-thing, but an exception is a clear, understandable rule.

- Preserve words should cut word, if there is only one: Well, this might be a nice feature, but for now i would skip it, as it complicates things..

- Preserve words with limit as long as first word: For me, same as the previous one..

Your testcases seem pretty good to me, but already have assumptions about the edgecases in them. I am not sure, if you can create a pull request on top of mine, but i would appreciate one. ;)

**Comment by fabpot** [comment]
I'm closing this PR as we now have native support (including proper Unicode support) in the string Twig extension: see https://twig.symfony.com/u

**Pull request closed without merging**
