### PR TITLE
Add merge_recursive filter

### PR DESCRIPTION
**Pull request by thewilkybarkid**
Core contains a `merge` filter, this adds `merge_recursive` (which uses PHP's `array_merge_recursive()`).

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
Test failures are unrelated.

**Comment by stof** [comment]
I'm not sure this is a good idea. `array_merge_recursive` is really confusing when you have associative arrays.

**Comment by thewilkybarkid** [comment]
It is core PHP though. Will create a dedicated library if this is closed.

**Comment by stof** [comment]
Well, lots of things are in PHP core and are not available in Twig templates. That's not an argument which will make me change my mind.
But ultimately, @fabpot is the one taking the decision anyway.

**Comment by thewilkybarkid** [comment]
> Well, lots of things are in PHP core and are not available in Twig templates. That's not an argument which will make me change my mind.

I’m not arguing that it should be in Twig because it is in PHP; only saying that the behaviour is the same.

**Comment by fabpot** [comment]
Merging things in templates is really an edge case that we should not encourage. After many fights, people were able to make me add the `merge` filter in Twig, but I don't think we want to add more than that. Let's close.

**Pull request closed without merging**
